# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8985196f32ffe742c7210867a5c0819b41046156581188b48b7722dd6be0d95cda86f1ebd0d578777adad89c897c18eaaeab0e010081ad779d81b852cd1697bc

test:
  secret_key_base: 1272e26350b2523b305ce797987db6af3ae87fa8a1cf75c85085b84f21c34d35c164b560814cbfc8b798fb7c72359a9e3c18faf1bcc0a257a5fd16f59cd2046c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
